using BAYSOFT.Abstractions.Crosscutting.Extensions;
using BAYSOFT.Abstractions.Crosscutting.Pluralization;
using BAYSOFT.Abstractions.Crosscutting.Pluralization.English;
using Forge.CLI.Models;

namespace Forge.CLI.Scaffolding.Templates
{
    public class EntityResourceDesignerTemplate
    {
		public static ForgeFile Render(ForgeProject project, string contextName, ForgeContext context, string entityName, ForgeEntity entity)
		{
			var entityCollectionName = Pluralizer.GetInstance()
				.AddEnglishPluralizer()
				.Pluralize(entityName, "en-US")
				.ToPascalCase();

			var filePath = $"src/{project.Name}.Core.Domain/{contextName}/Aggregates/{entityCollectionName}/Entities";
			var fileName = $"Entities{entityCollectionName}.Designer.cs";

			var references = new List<string>()
			{};
			
			var fileContent = $@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

{RenderReferences(references)}

namespace {project.Name}.Core.Domain.{contextName}.Aggregates.{entityCollectionName}.Resources {{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(""System.Resources.Tools.StronglyTypedResourceBuilder"", ""17.0.0.0"")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Entities{entityCollectionName} {{
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute(""Microsoft.Performance"", ""CA1811:AvoidUncalledPrivateCode"")]
        internal Entities{entityCollectionName}() {{
        }}
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {{
            get {{
                if (object.ReferenceEquals(resourceMan, null)) {{
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(""{project.Name}.Core.Domain.{contextName}.Aggregates.{entityCollectionName}.Resources.Entities{entityCollectionName}"", typeof(Entities{entityCollectionName}).Assembly);
                    resourceMan = temp;
                }}
                return resourceMan;
            }}
        }}
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {{
            get {{
                return resourceCulture;
            }}
            set {{
                resourceCulture = value;
            }}
        }}
        
        {RenderProperties(entity)}
        

        {RenderRelations(entity)}
    }}
}}";

			return new ForgeFile(filePath, fileName, fileContent);
		}

		private static string RenderReferences(List<string> references)
		{
			var result = string.Empty;
			foreach (var reference in references.Order())
			{
				result += $"using {reference};{Environment.NewLine}";
			}
			return result;
		}
		private static string RenderProperties(ForgeEntity entity)
		{
			var result = string.Empty;
			foreach (var property in entity.Properties)
			{
				result += @$"/// <summary>
		///   Looks up a localized string similar to {property.Key}.
		/// </summary>
		public static string {property.Key} {{
			get {{
				return ResourceManager.GetString(""{property.Key}"", resourceCulture);
			}}
		}}{Environment.NewLine}";
			}
			return result;
		}
		private static string RenderRelations(ForgeEntity entity)
		{
			var result = string.Empty;
			foreach (var relation in entity.Relations)
			{
				result += @$"/// <summary>
		///   Looks up a localized string similar to {relation.Key}.
		/// </summary>
		public static string {relation.Key} {{
			get {{
				return ResourceManager.GetString(""{relation.Key}"", resourceCulture);
			}}
		}}{Environment.NewLine}";
			}
			return result;
		}
	}
}
